/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Robot(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("./model.glb");
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    console.log("anim play");
    actions[names[0]]?.reset().play();
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="metarig">
          <primitive object={nodes.hips} />
          <group name="rigged">
            <skinnedMesh
              name="Plane043"
              geometry={nodes.Plane043.geometry}
              material={materials.body_blue}
              skeleton={nodes.Plane043.skeleton}
            />
            <skinnedMesh
              name="Plane043_1"
              geometry={nodes.Plane043_1.geometry}
              material={materials.body_grey}
              skeleton={nodes.Plane043_1.skeleton}
            />
            <skinnedMesh
              name="Plane043_2"
              geometry={nodes.Plane043_2.geometry}
              material={materials.body_red}
              skeleton={nodes.Plane043_2.skeleton}
            />
            <skinnedMesh
              name="Plane043_3"
              geometry={nodes.Plane043_3.geometry}
              material={materials.Eyes}
              skeleton={nodes.Plane043_3.skeleton}
            />
            <skinnedMesh
              name="Plane043_4"
              geometry={nodes.Plane043_4.geometry}
              material={materials.body_glass}
              skeleton={nodes.Plane043_4.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}
